BEGIN TRANSACTION;

	CREATE TABLE public.beer (
		id INTEGER PRIMARY KEY NOT NULL,
		name VARCHAR(50) NOT NULL,
		brewery VARCHAR(50) NOT NULL,
		country VARCHAR(10) NOT NULL,
		price NUMERIC(10,2) NOT NULL,
		currency VARCHAR(3) NOT NULL
	);

END TRANSACTION;